# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.3
_src_path: gh:algorandfoundation/algokit-python-template
author_email: my@mail.com
author_name: John Doe
contract_name: earlcoin
deployment_language: python
preset_name: production
project_name: earlcoin-algo-contracts

